### ISSUE TITLE
Hide all "& Meanwhile" posts

### ISSUE THREAD

**Issue by frnsys** [misfist/tni-theme#11]
So that they don't show up in search results, post loops, etc, and from navigation menus too.

What's the easiest way to do this? Is there a backend setting to exclude a certain category?

**Comment by misfist** [comment]
Removing from the menu is just a matter of removing the menu item in WP dashboard.

http://tni-staging.positiondevapp.com/wp/wp-admin/nav-menus.php

Having them no appear in loops and search results requires adding a filter. I'll do that.

**Comment by misfist** [comment]
Alternatively, we could add a plugin that would make this manageable from the dashboard. Let me know if you think that would be better for you.

**Comment by frnsys** [comment]
A filter is fine, thanks!

**Comment by misfist** [comment]
This is done in https://github.com/misfist/tni-theme/pull/16
