### ISSUE TITLE
Add "latest tweet" widget to header

### ISSUE THREAD

**Issue by frnsys** [misfist/tni-theme#13]
To take the place of where the newsletter signup form was (see #12)

Here's how it looks in the old site:
![image](https://cloud.githubusercontent.com/assets/1059947/24273155/3ddecad8-0ff7-11e7-81ae-58bdf0473331.png)

We need basically the same thing, just with an updated Twitter icon.

**Comment by misfist** [comment]
The Latest Tweets widget can be added to the header widget area using the dashboard/wp-admin (backend).

The plugin requires Twitter API creds be added. I don't have them.

/wp/wp-admin/options-general.php?page=twitter-api-admin

**Comment by frnsys** [comment]
The styling for this is done in 6ab13ba102d61b7a8a1d188902882a89c36ad2ab and the widget's been added in staging.
