### ISSUE TITLE
Replace infinite scroll with basic pagination

### ISSUE THREAD

**Issue by frnsys** [misfist/tni-theme#14]
Wherever infinite scroll is being used now, we want to replace it with basic pagination, i.e.:

![image](https://cloud.githubusercontent.com/assets/1059947/24273217/937909d6-0ff7-11e7-9eba-8d6b336b6dea.png)

I can handle the styling as long as the php is in place to render the necessary html

**Comment by misfist** [comment]
Sure, I can do this. 

Just curious... why?

**Comment by frnsys** [comment]
Mostly for two reasons:

- the infinite scroll doesn't save your place, e.g. if I've clicked "Load More" a few times and click on a link, then go back, I have to click "Load More" again to get back to where I was
- to keep the footer consistently accessible (but this isn't as much of a problem)

what do you think?

**Comment by misfist** [comment]
These reasons make a lot of sense.

I'm definitely not a usability or user engagement expert, and may be completely wrong, but I was thinking:

Maybe we should consider if the homepage behavior and archive behavior need to be the same. That is, it seems like having infinite scroll on the home page is what users expect and is a lower barrier to continue exploring content. But, users going to a section (archive page) have already initiated further exploration by clicking on the navigation.

BTW. Infinite scroll can be modified to automatically load more as a user scrolls down.

**Comment by misfist** [comment]
It's done in https://github.com/misfist/tni-theme/pull/16
