### ISSUE TITLE
TNI header logo

### ISSUE THREAD

**Issue by impkrr** [misfist/tni-theme#5]
TNI logo image at the top is 300px x 35px, and displayed at the same size. Could we use a bigger image (660 x 70) still displayed at 300 x 35 so it's retina display compatible.

http://tni-staging.positiondevapp.com/app/uploads/2017/02/tni-logo.png

**Comment by misfist** [comment]
Sure, please supply a larger logo image.

**Comment by impkrr** [comment]
thanks!

**Comment by misfist** [comment]
I'm adding a plugin that handles "retina" display automatically. What it does is generate a additional versions of images that are uploaded and serves the normal or "retina" version based on the visitor's screen resolution.

**Comment by impkrr** [comment]
sounds great. Thanks Pea.
