### ISSUE TITLE
Replace Load More Text with Image

### ISSUE THREAD

**Issue by misfist** [misfist/tni-theme#7]
Replace the LOAD MORE text button by the image attached (532 x 122 displayed at 266 x 61).

![load-more-button](https://cloud.githubusercontent.com/assets/709248/23271754/b7616470-f9c6-11e6-814a-d7259094771e.png)

**Comment by misfist** [comment]
Could you tell me what font this is or perhaps export as an SVG?

**Comment by impkrr** [comment]
.svg file attached

**Comment by misfist** [comment]
This is addressed in v0.3.1ea479b4
